### ISSUE TITLE
Update documentation of use cases

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#18]

**Comment by arnikz** [comment]
Update in 5b83310a54256ce5d8962036deb7fc59f0bc9aa5.

**Comment by arnikz** [comment]
N.B.: use [IETF BCP 47](https://tools.ietf.org/html/bcp47) standard for language tags.

**Comment by arnikz** [comment]
@lisestork: Could you add a narrative to each use case to understand its the machine-readable version (in RDF triples) better?

**Comment by lisestork** [comment]
Update use case (minimal mandatory triples created for each annotation example + optional triples) in 4543f66959fbe7166094c2686e25700532b2f4e6

**Comment by arnikz** [comment]
@lisestork: please replace dummy instances of:
- `dwc:HumanObservation` _Note: this class is not references in [DSW](http://www.visualdataweb.de/webvowl/#iri=http://purl.org/dsw/dsw.owl)._
- `dwc:Identification`
- `dwc:Organism`
- `dwc:Occurrence`
- `dwc:Event`
- `dcterms:Location` ([example 3_1](https://github.com/LINNAE-project/SFB-Annotator/tree/master/doc#Example-3_1)?)

in [example_1_2](https://github.com/LINNAE-project/SFB-Annotator/blob/master/data/rdf/local/example_1_2.svg) with real values if possible.

**Comment by arnikz** [comment]
@lisestork: TYPEs must be established prior making links between them (via GUI) in so-called OBSERVATION RECORDs. Is my assumption correct?

**Comment by lisestork** [comment]
> @lisestork: TYPEs must be established prior making links between them (via GUI) in so-called OBSERVATION RECORDs. Is my assumption correct?

True, although technically links can also be established first as properties have a fixed domain and range. Unless an entity is annotated with only a type.

**Comment by arnikz** [comment]
Somewhat related: if you make this distinction (i.e., TYPE vs. OBSERVATION RECORD) then you have to draw a bounding box for a TYPE(s) but not for the OBSERVATION RECORD(s) that connects two TYPEs (e.g., taxon & location). Moreover, this translates to different input forms that shouldn't overlap as it is now.

**Comment by arnikz** [comment]
@lisestork: There are two related subgraphs including `oa:hasBody` with `Buitenzorg` and the corresponding [`gn:1648473`](https://sws.geonames.org/1648473) IRI (Bogor). The former subgraph is classified as `oa:describing`. What should we use for the latter (related to #28)?

![Screenshot_2021-01-21_12-55-55](https://user-images.githubusercontent.com/7456848/105351172-7c415d00-5bec-11eb-86e5-76afbeda40ca.png)

**Comment by lisestork** [comment]
> @lisestork: please replace dummy instances of:
> 
> * `dwc:HumanObservation` _Note: this class is not references in [DSW](http://www.visualdataweb.de/webvowl/#iri=http://purl.org/dsw/dsw.owl)._ --> in addition to dwc:Token. Instance should be image of physical object, e.g.  https://trng-repository.surfsara.nl/deposit/900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001.tif
> * `dwc:Identification` --> abstract concept 
> * `dwc:Organism` --> abstract concept 
> * `dwc:Occurrence` --> abstract concept 
> * `dwc:Event` --> abstract concept 
> * `dcterms:Location` ([example 3_1](https://github.com/LINNAE-project/SFB-Annotator/tree/master/doc#Example-3_1)?)
> 
> in [example_1_2](https://github.com/LINNAE-project/SFB-Annotator/blob/master/data/rdf/local/example_1_2.svg) with real values if possible.

**Reason sfor minting URIs for abstract concepts**

The instances can serve as anchor points to which resources [...] may be linked. Because of this cross-institutional and cross-community anchoring function, DSW expects that most resources will be identified by persistent HTTP URIs or HTTP-proxied versions of globally unique identifiers in accordance with the TDWG GUID Applicability Statement Standard (https://www.tdwg.org/standards/guid-as/, https://github.com/tdwg/guid-as/blob/master/guid/tdwg_guid_applicability_statement.pdf). (Baskauf, S. J., & Webb, C. O. (2016). Darwin-SW: Darwin Core-based terms for expressing biodiversity data as RDF. Semantic Web, 7(6), 629–643. https://doi.org/10.3233/SW-150203)

Primary goal of the DSW is to facilitate the linking of _real_ data. Globally unique URIs should be generated for abstract concepts, such that metadata related to these concepts can be found in the text and attached to these concepts, in line with the Darwin Core specifications (https://dwc.tdwg.org/list/). 

e.g.: ex:organism1 dwc:organismRemarks "Wir erhielten sie met den Jungen" 

The entities of the ontology serve as a backbone for such metadata, and should be generated during annotation of entities that can be found _explicitly_ on the page, such as a `taxonomic name`, `location`, `person name`, `anatomical entity`, and `property or fact`. 

README.md will be updated to reflect this

**Comment by arnikz** [comment]
> **Reason sfor minting URIs for abstract concepts...**

I agree with this, however, please provide concrete examples for the remaining instances rather than

> e.g.: ex:organism1 dwc:organismRemarks "Wir erhielten sie met den Jungen".

**Comment by lisestork** [comment]
> > **Reason sfor minting URIs for abstract concepts...**
> 
> I agree with this, however, please provide concrete examples for the remaining instances rather than
> 
> > e.g.: ex:organism1 dwc:organismRemarks "Wir erhielten sie met den Jungen".

See: [iss18-URI-annotations](https://github.com/LINNAE-project/SFB-Annotator/tree/iss18/doc#uri-annotations)

**Comment by arnikz** [comment]
Btw `dwc:*Remarks`are written [here](https://github.com/LINNAE-project/SFB-Annotator/tree/iss18/doc#uri-annotations) in _English_ but the corresponding pages.are written in _German_. @lisestork: I think, these should be _verbatim_ (in [`iso:ger`](https://iso639-3.sil.org/code/ger)). Could you provide the transcriptions to update the input JSON files and/or RDF data models accordingly (related to #81)?

**Comment by arnikz** [comment]
> Could you provide the transcriptions to update the input JSON files and/or RDF data models accordingly (related to #81)?

This won't be necessary.
