### ISSUE TITLE
Connect transcriptions of ROI to instances of oa:TextualBody

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#25]
Currently, `oa:Annotation` instance links directly to `oa:TextualBody` and `dwc:Taxon` instances:

https://github.com/LINNAE-project/SFB-Annotator/blob/5b83310a54256ce5d8962036deb7fc59f0bc9aa5/data/rdf/example_1_1.ttl#L2-L6

@lisestork: Should we link the two instances with [`rdf:value`](https://www.w3.org/TR/rdf-schema/#ch_value) predicate [[1]](https://www.w3.org/TR/annotation-vocab/#textualbody)?

**Comment by lisestork** [comment]
See also https://github.com/LINNAE-project/SFB-Annotator/issues/28#issuecomment-674919712. I believe the `dwc:Taxon` instance should be directly connected to the `oa:Annotation` instance via the `oa:hasBody` property, and the "motivation": "classification".

@arnikz I agree that for the transcription of the region of interest, the transcription should indeed be attached to a blank node using the predicate `rdf:value` as in [example 15](https://www.w3.org/TR/annotation-vocab/#textualbody)

**Comment by arnikz** [comment]
I think, using `oa:TextualBody` just for this
https://github.com/LINNAE-project/SFB-Annotator/blob/5b83310a54256ce5d8962036deb7fc59f0bc9aa5/data/rdf/example_1_1.ttl#L8-L10

without this

https://github.com/LINNAE-project/SFB-Annotator/blob/5b83310a54256ce5d8962036deb7fc59f0bc9aa5/data/rdf/example_1_1.ttl#L34

is not that useful.

**Comment by lisestork** [comment]
Yes, I agree. In that case it is not so useful. 

I think it would be good to have two bodies if a piece of text is both classified and transcribed, as we can record the two different purposes (although there is no 'transcribing' motivation tag, just 'describing'). Maybe it should be an option in the interface, so that the classification or the transcription can also be recorded separately.

textualbody: [example 5](https://www.w3.org/TR/annotation-model/#example-4) (transcribing/describing) 
class from nhc: [example 44](https://www.w3.org/TR/annotation-model/#sets-of-bodies-and-targets) (classifying)
