### ISSUE TITLE
Record the intent behind the creation of an annotation

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#28]
Currently, we don't record this info.

References:
[1] https://www.w3.org/TR/annotation-model/#web-annotation-principles
[2] https://www.w3.org/TR/annotation-vocab/#named-individuals

**Comment by lisestork** [comment]
From the [Web Annotation Model](https://www.w3.org/TR/annotation-model/) document: 

I believe the following three apply to our case: 

3.3.5 Motivation and Purpose


Term | Type | Description | Interpretation (our)
-- | -- | -- | --
classifying | Instance | The motivation for when the user intends to classify the Target as something. For example to classify an image as a portrait | **This would link the annotation (indirectly the region of interest) to a class from the ontology**
identifying | Instance | The motivation for when the user intends to assign an identity to the Target. For example to associate the IRI that identifies a city with a mention of the city in a web page. | **This would link the annotation (indirectly the region of interest) to an instance from a class within the ontology**
describing | Instance | The motivation for when the user intends to describe the Target, as opposed to (for example) a comment about it. For example describing the above PDF's contents, rather than commenting on their accuracy. | **This would preferably transcribe the content of the region of interest\*.**

\* There is no way to add the motivation -> transcribing, although it has been brought up in this [issue](https://github.com/w3c/web-annotation/issues/428). Like they do, we might want to look into other vocabularies that can differentiate between describing (e.g., 'on this page, they are talking about the pupil dilation of the animal') and transcribing. 

**EXAMPLE 44:** Independents
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno41",
  "type": "Annotation",
  "motivation": "classifying",
  "body": "http://example.org/vocab/art/portrait",
  "target": {
    "type": "Independents",
    "items": [
      "http://example.com/image1",
      "http://example.net/image2",
      "http://example.com/image4",
      "http://example.org/image9"
    ]
  }
}

Where I believe that "http://example.org/vocab/art/portrait" can be a class from an ontology. In the case of motivation -> identifying, I guess that this is similar, but that this body could have the IRI of the instance, such as 'https://viaf.org/viaf/45106482/'. 

I think we can add multiple bodies within one annotation: one semantic and one textual, and have as a general motivation 'classifying' or 'identifying'. As a purpose for adding the TextualBody, we could say 'describing'. See example below: 

**EXAMPLE 15: Motivation and Purpose**
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno15",
  "type": "Annotation",
  "motivation": "bookmarking",
  "body": [
    {
      "type": "TextualBody",
      "value": "readme",
      "purpose": "tagging"
    },
    {
      "type": "TextualBody",
      "value": "A good description of the topic that bears further investigation",
      "purpose": "describing"
    }
  ],
  "target": "http://example.com/page1"
}

Combining the two examples and the one from 'https://iiif.io/api/annex/openannotation/#iiif-image-api-selector', annotating the handwritten text 'Kuhl' (referring to Heinrich Kuhl, https://viaf.org/viaf/45106482/), would become something like this: 

{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno41",
  "type": "Annotation",
  "motivation": "classifying",
  "body": 
[ "https://viaf.org/viaf/45106482/",
    {
      "type": "TextualBody",
      "value": "Kuhl",
      "purpose": "describing"
    }]
  "target": {
  "type": "SpecificResource",
  "source": "https://example.org/iiif/image1",
  "selector": {
    "type": "ImageApiSelector",
    "region": "pct:0,0,10,10",
    "rotation": "90"
  }
}
  }

And heinrich kuhl would already be annotated with rdf:type in the database, or we would have to think of a way to annotate it during this same annotation event.

**Comment by lisestork** [comment]
@lisestork add use cases for purpose of a body

**Comment by arnikz** [comment]
Whether to use [`oa:motivatedBy`](https://www.w3.org/TR/annotation-vocab/#motivatedby) in addition to [`oa:hasPurpose`](https://www.w3.org/TR/annotation-vocab/#haspurpose), including [`oa:identifying`](https://www.w3.org/TR/annotation-vocab/#identifying) and [`oa:describing`](https://www.w3.org/TR/annotation-vocab/#describing) as values, remains to be seen for the use cases (#31).
